config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'kids/index'
  root to: "kids#index"
  resources :kids 
  devise_for :users
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image
  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true
  
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :room_users
         has_many :rooms, through: :room_users
         has_many :messages

         validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end
  
  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if  @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids:[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/kids/_top_title.html.erb
<div class="title-view">
  <div class="title-space">
    <div class="title-left">
      <%= image_tag 'image0.png', width: "300px", height: "120px" %>
    </div>
    <div class="main-title">
      <strong>Kids Chat</strong>
    </div>
    <div class="title-right">
      <%= image_tag 'image0.png', width: "300px", height: "120px" %>
    </div>
  </div>
</div>

app/views/kids/index.html.erb
<div class="screen">
  <div class="title-bar">
    <%= render "top_title" %>
  </div>

  <div class="main-screen">
    <div class="image1">
      <%= image_tag 'image3.png', width: "180px", height: "180px" %>
    </div>

    <div class="image2">
      <%= image_tag 'image1.png', width: "600px", height: "150px" %>
    </div>

    <div class="rom">
      <div class="sign-up">
        <% if user_signed_in? %>
          <span><%= link_to current_user.name, "#", class: "login" %></span> 
          <span><%= link_to 'ろぐあうと', destroy_user_session_path, method: :delete, class: "registration" %></span> 
        <% else %>
          <span><%= link_to 'ろぐいん', new_user_session_path, class: "login" %></span>
          <span><%= link_to 'とうろく', new_user_registration_path, class: "registration" %></span>
        <% end %>
      </div>

      <div class="progress">
        <span class="progress-progress">➡️</span>
      </div>

      <div class="room-access">
        <a href="/rooms">
          <% if user_signed_in? %>
          <span class="room-room">るーむ</span>
          <% end %>
        </a>
      </div>
    </div>

    <div class="image3">
      <%= image_tag 'image5.png', width: "250px", height: "150px" %>
    </div>

    <div class="image4">
      <%= image_tag 'image6.png', width: "300px", height: "200px" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KidsChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name%>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "またね！", room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], html: {class: "form"}, local: true do |f|%>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
    <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name%>
    </div>
    <div class="message-date">
    <!-- 投稿した時刻を出力する -->
      <%= l message.created_at%>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
    <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content%>
    </div>
    <%= image_tag message.image.variant(resize:'500x500'), class: 'message-image' if message.image.attached?%>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name , "#" %>
  </div>
  <div class="create-room">
    <%= link_to "おへやをつくる", new_room_path %>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
  <div class="room">
    <div class="room-name">
      <%= image_tag 'image1.png', width: "200px", height: "80px" %>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar"%>
  </div>

  <div class='right-space'>
    <div class='sample1234'>
      <%= image_tag 'image0.png', width: "300px", height: "120px" %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.all.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%=current_user.id%>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>